# This file was generated by GoReleaser. DO NOT EDIT.
cask "hop" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/hop"],
                            writable_paths: ["hop"]
    end
  end

  version "1.1.2"

  on_macos do
    on_arm do
      sha256 "04c75e1573762097349ac557a1439856ba76bd6772568301876c33389f09c537"
      url "https://github.com/tabaak/hop/releases/download/v#{version}/hop_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4a56a09c48096270b2d17f9f23ff69b59245a306fe844a17fc1ebca7a9492bae"
      url "https://github.com/tabaak/hop/releases/download/v#{version}/hop_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0132d70d163f9697c5cb40364c54d0d013579586f28868391f953c37f27b3698"
      url "https://github.com/tabaak/hop/releases/download/v#{version}/hop_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "cc760dd0c0e094603d06cb202e007784a6a8f7dbcc54539c34df6a01a3d4b738"
      url "https://github.com/tabaak/hop/releases/download/v#{version}/hop_linux_amd64.tar.gz"
    end
  end

  name "hop"
  desc "Self-hosted ngrok alternative with wildcard TLS and a request inspector"
  homepage "https://github.com/tabaak/hop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hop"

  # No zap stanza required
end
