# This file was generated by GoReleaser. DO NOT EDIT.
cask "hop" do
  version "1.1.1"

  on_macos do
    on_arm do
      sha256 "f79e6a3d4f752957fa04b93710af0a62b85e552ada0de80b4d18d94bf55d8a0e"
      url "https://github.com/tabaak/hop/releases/download/v#{version}/hop_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2e0966b7a72e83ffa86376bd31a1aa9482adf412bbe1f340791bfcf8ddef3cb4"
      url "https://github.com/tabaak/hop/releases/download/v#{version}/hop_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c1af7a7c58c40d313e8dfe71da5dc57e8909963cdd8f2a8b7a36ac1687e962b8"
      url "https://github.com/tabaak/hop/releases/download/v#{version}/hop_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "76a56854db2847e8d0bd2c8677286129c9f23e138776aa01ef5953c8245cfbf1"
      url "https://github.com/tabaak/hop/releases/download/v#{version}/hop_linux_amd64.tar.gz"
    end
  end

  name "hop"
  desc "Self-hosted ngrok alternative with wildcard TLS and a request inspector"
  homepage "https://github.com/tabaak/hop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hop"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hop"]
    end
  end

  # No zap stanza required
end
